Core: Make OrderLine.sku max_length match that of Product.sku
Since the initial commit daa6dd85b, the `max_length` of `Product.sku` and
`OrderLine.sku` have not matched.

This would then cause this error:
```
django.db.utils.DataError: value too long for type character varying(48)
```
when creating an `Order` which had an `OrderLine` which contained a
`Product` with an over 48 character SKU.